export const REQUEST_SEARCH_DOCUMENTS_SUCCESS = 'REQUEST_SEARCH_DOCUMENTS_SUCCESS';
export const REQUEST_SEARCH_DOCUMENTS_ERROR = 'REQUEST_SEARCH_DOCUMENTS_ERROR';
export const SEARCH_STRING_UPDATE = 'SEARCH_STRING_UPDATE';
export const SEARCH_STRING_DELETE = 'SEARCH_STRING_DELETE';
